### ISSUE TITLE
Support for Akka-2.5.0 Cluster

### ISSUE THREAD

**Issue by mushtaq** [akka/akka-cluster-management#19]
I tried using it with Akka-2.5.0-RC2 but started getting errors like "java.lang.NoClassDefFoundError: akka/stream/Fusing$" maybe because of binary compatibility thing. Is it intended to work with 2.5 at all?

**Comment by patriknw** [comment]
Thanks for reporting. I think that can be because of the akka-http version, which used some internal APIs previously. Could you try to override the akka-http dependency to 10.0.5?

We will update the dependency in this library, of course.

**Comment by mushtaq** [comment]
Overriding akka-http to 10.0.5 did the trick. Thank you!

**Comment by patriknw** [comment]
Good, let's leave this ticket open until we have fixed the akka-http dependency.
Perhaps you can submit a pull request, @mushtaq ?

**Comment by mushtaq** [comment]
Sure, will do this over the weekend.

**Comment by stuartsaltzman** [comment]
Any update on this?

**Comment by ktoso** [comment]
Just override the dependency as https://github.com/akka/akka-cluster-management/issues/19#issuecomment-291499547 mentions and it'll work. This shouldn't be a stopper for anyone.

**Comment by patriknw** [comment]
I have updated the dependencies in PR #24
